peers: []

http:
  external:
    port: 3013
  internal:
    port: 3113
    listen_address: 0.0.0.0
    debug_endpoints: true

websocket:
  channel:
    listen_address: 0.0.0.0
    port: 3014

keys:
  peer_password: "top secret"
  dir: keys

chain:
  persist: true

mining:
  autostart: false

fork_management:
  network_id: "ae_uat"
